name: Output GitHub Issues
on:
  workflow_dispatch:
  issues:
    types: [opened, edited, deleted, closed, reopened, labeled, unlabeled]
jobs:
  github_issues:
    runs-on: ubuntu–latest
    steps:
      - name: Output issue number (if triggered by issue)
        run: echo "Issue Number - ${{ github.event.issue.number }}"
        if: github.event_name == 'issues'
      - name: Output issue title (if triggered by issue)
        run: echo "Issue Title - ${{ github.event.issue.title }}"
        if: github.event_name == 'issues'
      - name: Output issue body (if triggered by issue)
        run: echo "Issue Body - ${{ github.event.issue.body }}"
        if: github.event_name == 'issues'
      - name: Output issue state (if triggered by issue)
        run: echo "Issue State - ${{ github.event.issue.state }}"
        if: github.event_name == 'issues'
      - name: Output issue author (if triggered by issue)
        run: echo "Issue Author - ${{ github.event.issue.user.login }}"
        if: github.event_name == 'issues'
      - name: Output issue labels (if triggered by issue)
        run: echo "Issue Labels - ${{ toJSON(github.event.issue.labels) }}"
        if: github.event_name == 'issues'
      - name: Output issue action (if triggered by issue)
        run: echo "Issue Action - ${{ github.event.action }}"
        if: github.event_name == 'issues'
      - name: Output complete issue context (if triggered by issue)
        run: echo "${{ toJSON(github.event.issue) }}"
        if: github.event_name == 'issues'